sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - COPR_REPOSITORY=globaleaks
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=rawhide
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=8

services:
  - docker

install: true

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}

after_success:
  - pip install copr-cli simplejson
  - openssl aes-256-cbc -K $encrypted_916af48005ab_key -iv $encrypted_916af48005ab_iv -in .copr.enc -out copr-config -d
  - copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} *.src.rpm
